# Generated by Django 3.1.5 on 2021-09-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='mata_description',
            new_name='meta_description',
        ),
    ]
